version: "3.8"
services:
  viajar-no-brasil-db:
    image: postgres:13
    container_name: viajar-no-brasil-db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  viajar-no-brasil-back:
    container_name: viajar-no-brasil-back
    build: .
    ports:
      - 5000:4002
    depends_on:
      - viajar-no-brasil-db
    env_file:
      - .env
    volumes:
      - .:/viajar-no-brasil-back
volumes:
  postgres:
